apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  OPENAI_API_KEY: "{{ .Values.ss_open_api_key }}"
  LOG_LEVEL: "{{ .Values.ss_log_level }}"
  BHASHINI_ENDPOINT_URL: "{{ .Values.ss_bhasini_endpoint_url }}"
  BHASHINI_API_KEY: "{{ .Values.ss_bhasini_api_key }}"
  OCI_ENDPOINT_URL: "{{ .Values.ss_oci_endpoint_url }}"
  OCI_REGION_NAME: "{{ .Values.ss_oci_region_name }}"
  OCI_BUCKET_NAME: "{{ .Values.ss_oci_bucket_name }}"
  OCI_SECRET_ACCESS_KEY: "{{ .Values.ss_oci_access_key }}"
  OCI_ACCESS_KEY_ID: "{{ .Values.ss_oci_secret_key }}"
  
