apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  STORY_SAKHI_ENDPOINT: "{{ .Values.story_sakhi_endpoint_url }}"
  ACTIVITY_SAKHI_ENDPOINT: "{{ .Values.activity_sakhi_endpoint_url }}"
  REDIS_HOST: "{{ .Values.whatsapp_redis_hostname }}"
  REDIS_PORT: "{{ .Values.whatsapp_redis_port }}"
  REDIS_INDEX: "{{ .Values.whatsapp_redis_index }}"
  WHATSAPP_VERSION: "{{ .Values.whatsapp_version }}" # Whatsapp version number
  WHATSAPP_PHONEID: "{{ .Values.whatsapp_phoneid }}" # Registered whatsapp number 
  WHATSAPP_TOKEN: "{{ .Values.whatsapp_token }}" # Whatsapp token or whatsapp service provider (Netcore) token
  VERIFY_TOKEN: "{{ .Values.whatsapp_verify_token }}" # UUID to verify the request coming from the valid service provider
 