#jinja2:lstrip_blocks: True

#nginx_private_ingress_ip: "10.0.1.100"
domain: "dev.ejp.sunbird.org"
dashboard_domain: ""
#cloud_public_storage_accountname: ""
#cloud_public_storage_container: ""
# nginx private and public cert
core_vault_proxy_site_key: ""
core_vault_proxy_site_crt: ""
dashboard_vault_proxy_site_key: ""
dashboard_vault_proxy_site_crt: ""
merge_domain_status: false
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "400Mbps"

  
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 31380
  - port: 443
    name: https
    targetPort: 443
    nodePort: 31310

imagepullsecrets: regcred
dockerhub: docker.io

resources:
  requests:
    cpu: '100m'
    memory: '100Mi'
  limits:
    cpu: 1
    memory: '1024Mi'

repository: sanketnagdive/nginxrepo
image_tag: latest
pullPolicy: IfNotPresent

serviceMonitor:
  enabled: false
  labels: # labels with which the prometheus choose the serviceMonitor
    app: prometheus-operator
    release: prometheus-operator
