### Default variable file for activitysakhi-service ###
environment: "dev"
telemetry_url: "http://telemetry-service:9001"
telemetry_log_enabled: "true"

namespace: ""
imagepullsecrets: ""
dockerhub: ""

as_repository: "activity_sakhi_api_service"
as_image_tag: "latest"
as_log_level: INFO
as_openai_baseurl: ""
as_openai_version: ""
as_gpt_model: ""
activity_replica_count: 1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 8000
  targetport: 8000
network_wrapper:
  port: 7000
  targetport: 7000
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25

#{{ activitysakhi_liveness_readiness | to_nice_yaml }}

activityAutoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 
