apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  OPENAI_API_KEY: "{{ .Values.as_open_api_key }}"
  LOG_LEVEL: "{{ .Values.as_log_level }}"
  BHASHINI_ENDPOINT_URL: "{{ .Values.as_bhasini_endpoint_url }}"
  BHASHINI_API_KEY: "{{ .Values.as_bhasini_api_key }}"
  OCI_ENDPOINT_URL: "{{ .Values.as_oci_endpoint_url }}"
  OCI_REGION_NAME: "{{ .Values.as_oci_region_name }}"
  OCI_BUCKET_NAME: "{{ .Values.as_oci_bucket_name }}"
  OCI_SECRET_ACCESS_KEY: "{{ .Values.as_oci_secret_key }}"
  OCI_ACCESS_KEY_ID: "{{ .Values.as_oci_access_key }}"
  MARQO_URL: "{{ .Values.as_marqo_url }}"
  MARQO_INDEX_NAME: "{{ .Values.marqo_index_name }}"
  SERVICE_ENVIRONMENT: "{{ .Values.environment }}"
  TELEMETRY_ENDPOINT_URL: "{{ .Values.telemetry_url }}"
  TELEMETRY_LOG_ENABLED: "{{ .Values.telemetry_log_enabled }}"
  OPENAI_API_BASE: "{{ .Values.as_openai_baseurl }}"
  OPENAI_API_VERSION: "{{ .Values.as_openai_version }}"
  GPT_MODEL: "{{ .Values.as_gpt_model }}"
