### Default variable file for storysakhi-service ###
environment: "dev"
telemetry_url: "http://telemetry-service:9001"
telemetry_log_enabled: "true"

namespace: ""
imagepullsecrets: ""
dockerhub: ""

su_repository: "sakhi_utility_api_service"
su_image_tag: "latest"
su_log_level: "INFO"

su_open_api_key: ""
su_bhasini_endpoint_url: ""
su_bhasini_api_key: ""
su_oci_endpoint_url: ""
su_oci_region_name: ""
su_oci_bucket_name: ""
su_oci_access_key: ""
su_oci_secret_key: ""
su_openai_baseurl: ""
su_openai_version: ""
su_gpt_model: ""

network:
  port: 8000
  targetport: 8000
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25

#{{ storysakhi_liveness_readiness | to_nice_yaml }}

sakhiutilityConfig:
  replicaCount: 1
  autoscaleEnabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: ""
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1024Mi
