apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  OPENAI_API_KEY: "{{ .Values.as_open_api_key }}"
  LOG_LEVEL: "{{ .Values.as_open_api_key }}"
  BHASHINI_ENDPOINT_URL: "{{ .Values.as_bhasini_endpoint_url }}"
  BHASHINI_API_KEY: "{{ .Values.as_bhasini_api_key }}"
  OCI_ENDPOINT_URL: "{{ .Values.as_open_api_key }}"
  OCI_REGION_NAME: "{{ .Values.as_oci_region_name }}"
  OCI_BUCKET_NAME: "{{ .Values.as_oci_bucket_name }}"
  OCI_SECRET_ACCESS_KEY: "{{ .Values.as_oci_secret_access_key }}"
  MARQO_URL: "{{ .Values.as_marco_url }}"
  MARQO_INDEX_NAME: "{{ .Values.marco_index_name }}"
