namespace: ""
imagepullsecrets: ""
dockerhub: ""

content_repository: contentservice
content_image_tag: latest
content_config_cache_ttl: "1"
content_log_level: "warn"
content_postgres_ssl_enabled: "false"
content_postgres_table_name: "djp_contents"

network:
  port: 3000
  targetport: 3000
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25

contentConfig:
  replicaCount: 1
  autoscaleEnabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1024Mi
